Repository SymmetricDevs/Supersymmetry, pull requests merged in 2023-06, with the labels that each got.

#295 Manganese production (DO NOT MERGE UNTIL SUSYCORE 0.0.12)
  groovy/material/FirstDegreeMaterials.groovy
  groovy/material/OreMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/postInit/chains/Chemistry/ChemistryOverhaul.groovy
  groovy/postInit/chains/Chemistry/ManganeseChain.groovy
  groovy/postInit/chains/Chemistry/SilverChain.groovy
  resources/langfiles/lang/en_us.lang
Labels: enhancement, do not merge

#300 The Great Agglomeration of Machines Armaggadon
  groovy/material/FirstDegreeMaterials.groovy
  groovy/material/OrganicChemistryMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/material/ThermodynamicsMaterials.groovy
  groovy/material/ThirdDegreeMaterials.groovy
  groovy/material/UnknownCompositionMaterials.groovy
  groovy/postInit/chains/Chemistry/AluminiumChain.groovy
  groovy/postInit/chains/Chemistry/ChemistryOverhaul.groovy
  groovy/postInit/chains/EtchablesChain.groovy
  groovy/postInit/chains/PaperChain.groovy
  groovy/postInit/chains/PollutionChain.groovy
  groovy/postInit/chains/SiliconBouleChain.groovy
  groovy/postInit/chains/WaterPurificationChain.groovy
  groovy/postInit/mod/MachineRecipes.groovy
  groovy/preInit/RegisterMetaItems.groovy
  groovy/prePostInit/Thermodynamics.groovy
  resources/gregtech/models/item/metaitems/cellulose_acetate_mesh.json
  resources/gregtech/textures/items/metaitems/cellulose_acetate_mesh.png
  resources/langfiles/lang/en_us.lang
Labels: do not merge

#302 Gallium related content (do not merge until SusyCore 0.0.12)
  groovy/material/FirstDegreeMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/postInit/chains/Chemistry/AluminiumChain.groovy
  groovy/postInit/chains/Chemistry/ArsenicChain.groovy
  groovy/postInit/chains/Chemistry/BoronChain.groovy
  groovy/postInit/chains/Chemistry/GalliumChain.groovy
  groovy/postInit/mod/Molds.groovy
  groovy/preInit/RegisterMetaItems.groovy
  resources/gregtech/models/item/metaitems/boron.nitride.crucible.json
  resources/gregtech/models/item/metaitems/shape.mold.crucible.json
  resources/gregtech/textures/items/metaitems/boron.nitride.crucible.png
  resources/gregtech/textures/items/metaitems/shape.mold.crucible.png
  resources/langfiles/lang/en_us.lang
Labels: enhancement

#317 New primitive steel durations
  groovy/postInit/chains/IronChain.groovy
Labels: enhancement

#375 Chrome production
  config/gregtech/worldgen/vein/overworld/phosphorite_vein.json
  config/loliasm.cfg
  groovy/classes/ChangeFlags.groovy
  groovy/material/FirstDegreeMaterials.groovy
  groovy/material/SecondDegreeMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/material/UnknownCompositionMaterials.groovy
  groovy/postInit/chains/Chemistry/BerylliumChain.groovy
  groovy/postInit/chains/Chemistry/BoronChain.groovy
  groovy/postInit/chains/Chemistry/ChromiumChain.groovy
  groovy/postInit/chains/Chemistry/ZincChain.groovy
  groovy/postInit/chains/IronChain.groovy
  resources/langfiles/lang/en_us.lang
Labels: enhancement
