Repository SymmetricDevs/Supersymmetry, pull requests merged in 2025-06, with the labels that each got.

#1472 Allow red sand to be used to craft sand pile
  groovy/postInit/misc/BrickChain.groovy
  groovy/postInit/mod/GregTech.groovy
Labels: fix

#1462 ohh jezz, made the game playable again
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
Labels: fix

#1466 Update Quenching.groovy
  groovy/postInit/metallurgy/Quenching.groovy
Labels: fix

#1227 Rare earth processing chain
  groovy/classes/ChangeFlags.groovy
  groovy/material/FirstDegreeMaterials.groovy
  groovy/material/OreMaterials.groovy
  groovy/material/OrganicChemistryMaterials.groovy
  groovy/material/SecondDegreeMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/material/ThirdDegreeMaterials.groovy
  groovy/material/UnknownCompositionMaterials.groovy
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
  groovy/postInit/chemistry/inorganic_chemistry/ElectrolysisOverhaul.groovy
  groovy/postInit/chemistry/inorganic_chemistry/Magnets.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group10/PlatinumGroupChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group3/YttriumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group5/TantalumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group9/CobaltChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/actinides/ThoriumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/actinides/UraniumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/CeriumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/DysprosiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/ErbiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/EuropiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/GadoliniumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/HolmiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/LanthanumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/LutetiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/NeodymiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/PraseodymiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/SamariumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/TerbiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/ThuliumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/YtterbiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/separations/BastnasiteProcessing.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/separations/MonaziteProcessing.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/separations/XenotimeProcessing.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/p_block/group15/NitrogenChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/p_block/group15/PhosphorusChain.groovy
  groovy/postInit/chemistry/organic_chemistry/Extractants.groovy
  groovy/postInit/chemistry/organic_chemistry/petrochemistry/Lubricants.groovy
  groovy/postInit/metallurgy/OreSorting.groovy
  groovy/preInit/RegisterMetaItems.groovy
  groovy/prePostInit/ModifyRecipeMaps.groovy
  resources/gregtech/models/item/metaitems/beads.loaded_lutetium_cation_exchange.json
  resources/gregtech/models/item/metaitems/beads.rare_earth_cation_exchange.json
  resources/gregtech/models/item/metaitems/crucible.tantalum.json
  resources/gregtech/textures/items/metaitems/beads.loaded_lutetium_cation_exchange.png
  resources/gregtech/textures/items/metaitems/beads.rare_earth_cation_exchange.png
  resources/gregtech/textures/items/metaitems/crucible.tantalum.png
  resources/langfiles/lang/en_pt.lang
  resources/langfiles/lang/en_us.lang
  resources/langfiles/lang/pl_pl.lang
  resources/langfiles/lang/ru_ru.lang
  resources/langfiles/lang/zh_cn.lang
Labels: feature

#1479 Nobody wanted, everyone needed
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group6/ChromiumChain.groovy
Labels: change

#1482 fixes for reeline
  config/betterquesting.cfg
  config/betterquesting/DefaultQuests/QuestLines/4.json
  config/betterquesting/DefaultQuests/QuestLines/5.json
  config/betterquesting/DefaultQuests/QuestLines/6.json
  config/betterquesting/DefaultQuests/Quests/2/203.json
  config/betterquesting/DefaultQuests/Quests/4/1220908734.json
  config/betterquesting/DefaultQuests/Quests/5/1051748281.json
  config/betterquesting/DefaultQuests/Quests/5/1064746016.json
  config/betterquesting/DefaultQuests/Quests/5/1338245952.json
  config/betterquesting/DefaultQuests/Quests/5/1646718435.json
  config/betterquesting/DefaultQuests/Quests/5/1923587932.json
  config/betterquesting/DefaultQuests/Quests/5/1962935316.json
  config/betterquesting/DefaultQuests/Quests/5/1973878836.json
  config/betterquesting/DefaultQuests/Quests/5/213706018.json
  config/betterquesting/DefaultQuests/Quests/5/245789464.json
  config/betterquesting/DefaultQuests/Quests/5/595675883.json
  config/betterquesting/DefaultQuests/Quests/6/1188697175.json
  config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/328732527.json
  config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/702454111.json
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
  config/jei/itemBlacklist.cfg
  groovy/material/FirstDegreeMaterials.groovy
  groovy/material/SecondDegreeMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/postInit/chemistry/inorganic_chemistry/ElectrolysisOverhaul.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group5/TantalumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/separations/MonaziteProcessing.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/separations/XenotimeProcessing.groovy
  groovy/postInit/chemistry/organic_chemistry/Extractants.groovy
  resources/langfiles/lang/en_us.lang
Labels: fix

#1467 Advanced Electrolysis quest desc. cleanup
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
Labels: fix

#1485 caliche chain
  groovy/material/FirstDegreeMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/material/UnknownCompositionMaterials.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/separations/BastnasiteProcessing.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/separations/MonaziteProcessing.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/separations/XenotimeProcessing.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/p_block/group16/SulfurChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/p_block/group17/IodineChain.groovy
  groovy/postInit/metallurgy/OreSorting.groovy
  resources/langfiles/lang/en_us.lang
Labels: feature

#1488 Remove steel duplication
  groovy/postInit/mod/GregTech.groovy
Labels: fix

#1490 Fix machine for magnetic neodymium
  groovy/postInit/chemistry/inorganic_chemistry/Magnets.groovy
Labels: fix

#1491 fix cobalt electrolysis recipe
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group9/CobaltChain.groovy
Labels: fix

#1495 Making ethane flammable
  groovy/classes/ChangeFlags.groovy
Labels: fix

#1501 Apparently my comma after chest in pyrotech.groovy didn't get saved
  groovy/postInit/mod/Pyrotech.groovy
Labels: fix

#1496 Make a canary file for pack updates
  config/betterquesting/DefaultQuests/Quests/16/207.json
  config/susy/susy_canary
  index.toml
Labels: fix

#1504 Kevlar recipe fix
  groovy/material/FirstDegreeMaterialsA.groovy
  groovy/material/FirstDegreeMaterialsB.groovy
  groovy/material/SecondDegreeMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/material/UnknownCompositionMaterials.groovy
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
  groovy/postInit/chemistry/organic_chemistry/polymers/AramidChain.groovy
  groovy/postInit/metallurgy/StrandCasting.groovy
  resources/langfiles/lang/en_us.lang
Labels: fix

#1492 General Bug Fixes
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
  config/jei/itemBlacklist.cfg
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group4/ZirconiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/separations/BastnasiteProcessing.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/separations/MonaziteProcessing.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/lanthanides/separations/XenotimeProcessing.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/p_block/group13/ThalliumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/s_block/group2/MagnesiumChain.groovy
  groovy/postInit/chemistry/organic_chemistry/polymers/EpoxyChain.groovy
  groovy/postInit/metallurgy/OreSorting.groovy
  groovy/postInit/mod/GregTech.groovy
  groovy/postInit/mod/SusyCore.groovy
  groovy/prePostInit/ModifyRecipeMaps.groovy
Labels: fix

#1508 Update Universal Tweaks and Icons
  config/Universal Tweaks - Bugfixes.cfg
  config/Universal Tweaks - Mod Integration.cfg
  config/Universal Tweaks - Tweaks.cfg
  config/itlt/icon.png
  config/randompatches.cfg
  icon.png
  mods/universal-tweaks.pw.toml
  resources/universaltweaks/icon16.png
  resources/universaltweaks/icon256.png
  resources/universaltweaks/icon32.png
Labels: fix

#1509 Textrepack finally added
  .gitignore
  resourcepacks/supersymmetry-refreshed.pw.toml
Labels: feature

#1454 update german lang-file
  resources/langfiles/lang/de_de.lang
Labels: feature

#1510 Fix the rotten glyoxal recipe
  groovy/postInit/mod/GregTechFoodOption.groovy
Labels: fix

#1497 feat: JER registration for TechGuns
  groovy/postInit/mod/JER.groovy
Labels: change

#1518 Mod updates
  config/supercritical.cfg
  index.toml
  mods/stellarcore.pw.toml
  mods/supercritical.pw.toml
  pack.toml
  resourcepacks/shadertech.pw.toml
Labels: internal

#1517 Update WaterPurificationChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/WaterPurificationChain.groovy
Labels: change

#1514 Add quarry recipes
  groovy/globals/Globals.groovy
  groovy/postInit/gameplay/Drone.groovy
  groovy/postInit/gameplay/MiningDrill.groovy
  groovy/postInit/gameplay/Quarry.groovy
  groovy/postInit/mod/GregTech.groovy
  groovy/postInit/mod/Pyrotech.groovy
Labels: feature

#1391 Motor rework
  .gitignore
  config/betterquesting/DefaultQuests/QuestLines/0.json
  config/betterquesting/DefaultQuests/QuestLines/1.json
  config/betterquesting/DefaultQuests/Quests/1/25903173.json
  config/betterquesting/DefaultQuests/Quests/1/26.json
  config/betterquesting/DefaultQuests/Quests/1/51.json
  config/betterquesting/DefaultQuests/Quests/2/203.json
  config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/31.json
  config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/702454111.json
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
  config/cyberware.cfg
  groovy/classes/ChangeFlags.groovy
  groovy/material/FirstDegreeMaterialsA.groovy
  groovy/material/FirstDegreeMaterialsB.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/postInit/chemistry/inorganic_chemistry/Magnets.groovy
  groovy/postInit/components/MagneticIronRodChain.groovy
  groovy/postInit/components/Motors.groovy
  groovy/postInit/metallurgy/OreSorting.groovy
  groovy/postInit/mod/GregTech.groovy
  groovy/preInit/ModifyRecycling.groovy
  groovy/preInit/RegisterMetaItems.groovy
  resources/gregtech/models/item/metaitems/brush.json
  resources/gregtech/models/item/metaitems/brush.unfired.json
  resources/gregtech/models/item/metaitems/commutator.json
  resources/gregtech/models/item/metaitems/hot_steel_plate.json
  resources/gregtech/textures/items/metaitems/brush.png
  resources/gregtech/textures/items/metaitems/brush.unfired.png
  resources/gregtech/textures/items/metaitems/commutator.png
  resources/gregtech/textures/items/metaitems/hot_steel_plate.png
  resources/langfiles/lang/en_us.lang
Labels: change

#1494 Random Changes
  config/betterquesting/DefaultQuests/QuestLines/4.json
  config/betterquesting/DefaultQuests/Quests/19/878.json
  config/betterquesting/DefaultQuests/Quests/4/681.json
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
  config/nutrition/nutrients/dairy.json
  config/pyrotech/module.Bucket.cfg
  groovy/classes/ChangeFlags.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group4/TitaniumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/p_block/group15/PhosphorusChain.groovy
Labels: fix

#1522 Fix nuclear bugs
  .gitignore
  config/baubles.cfg
  config/betterquesting.cfg
  config/biomesoplenty/biomes/defaults/biomesoplenty/corrupted_sands.json
  config/biomesoplenty/biomes/defaults/biomesoplenty/fungi_forest.json
  config/biomesoplenty/biomes/defaults/biomesoplenty/mystic_grove.json
  config/biomesoplenty/biomes/defaults/biomesoplenty/ominous_woods.json
  config/biomesoplenty/biomes/defaults/biomesoplenty/phantasmagoric_inferno.json
  config/craftpresence.json
  config/cyberware.cfg
  config/gregtech/modules.cfg
  config/modularui.cfg
  config/opencomputers/settings.conf
  config/quark.cfg
  config/stellar_core.cfg
  config/vintagefix.properties
  groovy/classes/ChangeFlags.groovy
  groovy/material/FirstDegreeMaterialsA.groovy
  groovy/material/FirstDegreeMaterialsB.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/material/ThermodynamicsMaterials.groovy
  groovy/postInit/chemistry/inorganic_chemistry/Magnets.groovy
  groovy/postInit/components/SMDComponents.groovy
  groovy/postInit/metallurgy/MetallurgyRemovals.groovy
  groovy/postInit/metallurgy/Quenching.groovy
  groovy/postInit/metallurgy/StainlessSteelChain.groovy
  groovy/postInit/metallurgy/StrandCasting.groovy
  groovy/prePostInit/Thermodynamics.groovy
  resources/langfiles/lang/de_de.lang
  resources/langfiles/lang/en_us.lang
Labels: fix

#1434 Pipe net walker behavior for wrenches & wire cutters
  groovy/postInit/gameplay/PipeNetBehaviorLoader.groovy
  groovy/preInit/PipeNetWalkerBehaviour.groovy
  groovy/preInit/PipeOperationWalker.groovy
  resources/langfiles/lang/en_us.lang
Labels: feature

#1531 Revert: pipenet walker behavior
  groovy/postInit/gameplay/PipeNetBehaviorLoader.groovy
  groovy/preInit/PipeNetWalkerBehaviour.groovy
  groovy/preInit/PipeOperationWalker.groovy
Labels: fix

#1534 remove circular dependency for alnico
  groovy/postInit/metallurgy/Quenching.groovy
Labels: fix
