Repository SymmetricDevs/Supersymmetry, pull requests merged in 2025-05, with the labels that each got.

#1420 Formatting update
  groovy/postInit/components/VacuumComponents.groovy
  groovy/postInit/metallurgy/Superalloys.groovy
  groovy/postInit/mod/GregTech.groovy
  groovy/postInit/mod/MachineRecipes.groovy
Labels: internal

#1422 Fixed nitric acid stoic and chlorine stoic in alluvial PGM
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group10/PlatinumGroupChain.groovy
Labels: fix

#1423 Update ICBM
  mods/icbm.pw.toml
Labels: change

#1425 phosgene breakdown
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
Labels: feature

#1426 change liquid glass temp and liquid e-glass recipe
  groovy/classes/ChangeFlags.groovy
  groovy/postInit/chemistry/organic_chemistry/polymers/EpoxyChain.groovy
Labels: fix

#1428 qb change
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
Labels: fix

#1430 fix PTFE chlorine voiding Attempt 2
  groovy/material/OrganicChemistryMaterials.groovy
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
Labels: fix

#1431 Fixed missing GasTier import; fixed missing metaitem key
  groovy/material/SecondDegreeMaterials.groovy
  groovy/postInit/mod/MachineRecipes.groovy
Labels: fix

#1427 Fix superalloy quenching time
  groovy/material/SecondDegreeMaterials.groovy
  groovy/postInit/metallurgy/Quenching.groovy
Labels: fix

#1435 Change circuit board patterning circuit
  groovy/postInit/components/EtchablesChain.groovy
Labels: fix

#1436 Replace scalar with scalar legacy
  mods/scalar-legacy.pw.toml
  mods/scalar.pw.toml
Labels: internal

#1441 Update scrit
  mods/supercritical.pw.toml
Labels: change

#1439 feat: drone pad quest
  config/betterquesting/DefaultQuests/QuestLines/2.json
  config/betterquesting/DefaultQuests/Quests/2/1285370028.json
  config/betterquesting/DefaultQuests/Quests/3/505.json
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
Labels: feature

#1440 feat: recipes for locomotive controller + exchangers
  groovy/postInit/mod/MachineRecipes.groovy
Labels: feature

#1448 fix: accidental removal of carbon arc lamps
  groovy/postInit/mod/GregTech.groovy
Labels: fix

#1447 fix KF input for tantalum chain
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group5/TantalumChain.groovy
Labels: fix

#1443 Update ChemistryOverhaul.groovy
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
Labels: change

#1450 Update AluminiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/p_block/group13/AluminiumChain.groovy
Labels: change

#1460 update chemistry signs mod to 1.1.1
  mods/chemistry-signs.pw.toml
Labels: change

#1459 Remove old Aluminium electrolysis recipe
  groovy/postInit/chemistry/inorganic_chemistry/elements/p_block/group13/AluminiumChain.groovy
Labels: fix
