Repository SymmetricDevs/Supersymmetry, pull requests merged in 2025-09, with the labels that each got.

#1635 Removal of Red Alloy from Circuits
  groovy/postInit/components/IntegratedCircuits.groovy
Labels: fix, targeted for next update

#1637 Update supersymmetry-refreshed.pw.toml
  resourcepacks/supersymmetry-refreshed.pw.toml
Labels: internal

#1629 Mod updates
  config/Universal Tweaks - Bugfixes.cfg
  config/Universal Tweaks - General.cfg
  config/Universal Tweaks - Mod Integration.cfg
  config/Universal Tweaks - Tweaks.cfg
  config/sussypatches.cfg
  mods/better-placement.pw.toml
  mods/craftpresence.pw.toml
  mods/extreme-sound-muffler-legacy.pw.toml
  mods/fugue.pw.toml
  mods/had-enough-items.pw.toml
  mods/jei-utilities.pw.toml
  mods/modularui.pw.toml
  mods/supercritical.pw.toml
  mods/sussypatches.pw.toml
  mods/susycore.pw.toml
  mods/unilib.pw.toml
  mods/universal-tweaks.pw.toml
Labels: internal, targeted for next update

#1628 Rainbowwood recipes
  groovy/postInit/biology/GreenhouseChain.groovy
  groovy/postInit/mod/GregTech.groovy
  resources/langfiles/lang/en_us.lang
Labels: change, targeted for next update

#1640 More fixes
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
Labels: fix

#1650 Added dustwood recipe with Mortar
  groovy/postInit/gameplay/StartingAge.groovy
Labels: change

#1647 qb fixes
  build/questbook.py
  config/betterquesting/DefaultQuests/Quests/0/722.json
  config/betterquesting/DefaultQuests/Quests/2/203.json
  config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/2114289290.json
  config/betterquesting/DefaultQuests/Quests/MultipleQuestLine/702454111.json
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
Labels: fix

#1649 Techguns ammo swapping recipes part 2
  groovy/postInit/mod/TechGuns.groovy
Labels: fix, targeted for next update

#1648 Delete old FeW recycle recipe
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
  groovy/postInit/chemistry/inorganic_chemistry/Magnets.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group8/IronChain.groovy
  groovy/prePostInit/ModifyRecipeMaps.groovy
  resources/gregtech/textures/items/metaitems/voltage_coil.ev.png
Labels: change

#1657 feat: add bauble behavior to lead acid battery
  groovy/preInit/RegisterMetaItems.groovy
Labels: change
