Repository SymmetricDevs/Supersymmetry, pull requests merged in 2025-10, with the labels that each got.

#1672 Use Ni(OH)2 instead of NiOOH in battery production
  groovy/material/FirstDegreeMaterialsA.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/postInit/components/Batteries.groovy
  resources/langfiles/lang/de_de.lang
  resources/langfiles/lang/en_pt.lang
  resources/langfiles/lang/en_us.lang
  resources/langfiles/lang/pl_pl.lang
  resources/langfiles/lang/ru_ru.lang
  resources/langfiles/lang/zh_cn.lang
Labels: fix

#1679 Update changelog
  CHANGELOG.md
Labels: internal

#1680 minor recipe conflict fixes (+allow quarry to mine inf limestone)
  groovy/classes/ChangeFlags.groovy
  groovy/material/FirstDegreeMaterialsA.groovy
  groovy/material/OrganicChemistryMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/postInit/chemistry/Catalysts.groovy
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
  groovy/postInit/chemistry/organic_chemistry/polymers/InjectionMolding.groovy
  groovy/postInit/chemistry/organic_chemistry/polymers/fluoropolymers/NafionChain.groovy
  groovy/postInit/chemistry/organic_chemistry/polymers/thermoplastics/PolyphenyleneOxideChain.groovy
  groovy/postInit/components/Batteries.groovy
  groovy/postInit/components/ElectronicCircuits.groovy
  groovy/postInit/components/FuelCells.groovy
  groovy/postInit/gameplay/QuarryMachine.groovy
  groovy/postInit/metallurgy/LadleMetallurgy.groovy
  groovy/postInit/metallurgy/MetallurgyRemovals.groovy
  groovy/postInit/mod/GregTechFoodOption.groovy
  groovy/prePostInit/Thermodynamics.groovy
  resources/langfiles/lang/de_de.lang
  resources/langfiles/lang/en_pt.lang
  resources/langfiles/lang/en_us.lang
  resources/langfiles/lang/pl_pl.lang
  resources/langfiles/lang/ru_ru.lang
  resources/langfiles/lang/zh_cn.lang
Labels: fix

#1681 Update techbro biomes again (sigma biomes)
  CHANGELOG.md
  config/sussypatches.cfg
  groovy/classes/ChangeFlags.groovy
  groovy/material/FirstDegreeMaterialsA.groovy
  groovy/material/OrganicChemistryMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/postInit/chemistry/Catalysts.groovy
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
  groovy/postInit/chemistry/organic_chemistry/polymers/InjectionMolding.groovy
  groovy/postInit/chemistry/organic_chemistry/polymers/fluoropolymers/NafionChain.groovy
  groovy/postInit/chemistry/organic_chemistry/polymers/thermoplastics/PolyphenyleneOxideChain.groovy
  groovy/postInit/components/Batteries.groovy
  groovy/postInit/components/ElectronicCircuits.groovy
  groovy/postInit/components/FuelCells.groovy
  groovy/postInit/gameplay/QuarryMachine.groovy
  groovy/postInit/metallurgy/LadleMetallurgy.groovy
  groovy/postInit/metallurgy/MetallurgyRemovals.groovy
  groovy/postInit/mod/GregTechFoodOption.groovy
  groovy/prePostInit/Thermodynamics.groovy
  mods/extreme-sound-muffler-legacy.pw.toml
  mods/fluidlogged-api.pw.toml
  mods/fugue.pw.toml
  mods/had-enough-items.pw.toml
  mods/mixin-booter.pw.toml
  mods/modularui.pw.toml
  mods/sussypatches.pw.toml
  mods/susycore.pw.toml
  pack.toml
  resources/langfiles/lang/de_de.lang
  resources/langfiles/lang/en_pt.lang
  resources/langfiles/lang/en_us.lang
  resources/langfiles/lang/pl_pl.lang
  resources/langfiles/lang/ru_ru.lang
  resources/langfiles/lang/zh_cn.lang
  structures/active/TechbroHouses/TechBroBiomes.rcbp
Labels: fix, feature
