Repository SymmetricDevs/Supersymmetry, pull requests merged in 2025-04, with the labels that each got.

#1363 Minor fixes
  config/betterquesting/DefaultQuests/Quests/18/230.json
  config/betterquesting/DefaultQuests/Quests/2/472.json
  config/betterquesting/DefaultQuests/Quests/4/1617418058.json
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
  groovy/postInit/mod/Chisel.groovy
Labels: fix

#1365 Automated changelog generation
  .github/scripts/generate_changelog.py
  .github/workflows/generate-modpack-changelog.yaml
  .github/workflows/manage_pr_labels.yaml
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
  pack.toml
Labels: internal

#1367 Add ProjectRed to the pack
  config/ProjectRed.cfg
  groovy/postInit/mod/GregTech.groovy
  groovy/postInit/mod/ProjectRed.groovy
  index.toml
  mods/cb-multipart.pw.toml
  mods/mrtjpcore.pw.toml
  mods/project-red-core.pw.toml
  mods/project-red-illumination.pw.toml
  mods/project-red-integration.pw.toml
Labels: feature

#1380 add supercrit + update mixinbooter
  config/supercritical.cfg
  mods/mixin-booter.pw.toml
  mods/supercritical.pw.toml
Labels: feature

#1374 a collection of techgun fixes/changes
  config/betterquesting/DefaultQuests/Quests/1/62.json
  config/betterquesting/DefaultQuests/Quests/1/63.json
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
  groovy/postInit/mod/TechGuns.groovy
Labels: fix

#1382 refactor RecyclingHelper.groovy
  groovy/postInit/utils/RecyclingHelper.groovy
  groovy/postInit/utils/RecyclingReloader.groovy
  groovy/preInit/MetaClassExpensions.groovy
  groovy/runConfig.json
Labels: change

#1381 Fixed battery recipes calling null which would cause crashes
  groovy/postInit/mod/GregTech.groovy
Labels: fix

#1335 Update ru_RU.lang
  resources/langfiles/lang/ru_ru.lang
Labels: change

#1366 superalloy recipe rework
  groovy/material/FirstDegreeMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/postInit/metallurgy/Quenching.groovy
  groovy/postInit/metallurgy/Superalloys.groovy
  groovy/postInit/mod/GregTech.groovy
  resources/langfiles/lang/en_us.lang
Labels: change

#1376 Susyfying gcym casings
  groovy/material/FirstDegreeMaterials.groovy
  groovy/postInit/metallurgy/Superalloys.groovy
Labels: feature

#1370 more fixes for next update
  groovy/material/FirstDegreeMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group12/ZincChain.groovy
  groovy/postInit/chemistry/organic_chemistry/CarboxylicAcidChain.groovy
  groovy/postInit/mod/TechGuns.groovy
  mods/susycore.pw.toml
  pack.toml
  resources/langfiles/lang/en_us.lang
Labels: fix

#1383 minor spelling mistakes
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
  groovy/postInit/chemistry/organic_chemistry/BiofuelChain.groovy
  groovy/postInit/mod/SusyCore.groovy
  groovy/postInit/mod/TechGuns.groovy
  mods/opencomputers.pw.toml
Labels: fix

#1384 Fix metaPrefixItems losing their recycling recipes
  groovy/postInit/utils/RecyclingReloader.groovy
Labels: fix

#1385 Fix my skill issue on fixing my skill issue
  groovy/postInit/utils/RecyclingReloader.groovy
Labels: fix

#1395 Upgrade release script for CF uploads
  .github/scripts/extract_changelog.py
  .github/workflows/release.yaml
  CHANGELOG.md
Labels: internal

#1394 update ICBM to 6.5.3
  mods/icbm.pw.toml
Labels: change

#1388 redo cobalt purity system
  groovy/material/FirstDegreeMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/postInit/chemistry/Catalysts.groovy
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
  groovy/postInit/chemistry/inorganic_chemistry/Magnets.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group9/CobaltChain.groovy
  groovy/postInit/chemistry/organic_chemistry/Extractants.groovy
  groovy/postInit/components/Batteries.groovy
  resources/langfiles/lang/en_us.lang
Labels: change

#1398 electric motor textures
  resources/gregtech/textures/items/metaitems/brush.png
  resources/gregtech/textures/items/metaitems/brush.unfired.png
  resources/gregtech/textures/items/metaitems/commutator.png
Labels: feature

#1389 uranium enrichment
  .gitignore
  config/GeographiCraft/geographicraft.cfg
  config/MrTJPCore.cfg
  config/ScalingGUIs/ScalingGUIs.cfg
  config/ScalingGUIs/ScalingGUIsCustomScales.json
  config/alet-client.json
  config/craftpresence.json
  config/customloadingscreen.cfg
  config/cyberware.cfg
  config/dropt.module.Dropt.cfg
  config/flare/flare.cfg
  config/gregicprobe.cfg
  config/gregtech/modules.cfg
  config/gregtech/persistent_data.dat
  config/groovyscript.cfg
  config/icbmclassic/blast.cfg
  config/icbmclassic/blocks.cfg
  config/icbmclassic/main.cfg
  config/icbmclassic/missile.cfg
  config/jei/itemBlacklist.cfg
  config/jei/jei.cfg
  config/littletiles.json
  config/loliasm.cfg
  config/microblocks.cfg
  config/modularui.cfg
  config/mousetweaks.cfg
  config/multipart.cfg
  config/neenergistics/neenergistics.cfg
  config/nutrition/food_hint.json
  config/nutrition/nutrition.cfg
  config/opencomputers/settings.conf
  config/packagedauto.cfg
  config/phosphor.json
  config/pyrotech/core.cfg
  config/reccomplex.cfg
  config/serializationisbad-remotecache.json
  config/serializationisbad.json
  config/soundphysics.cfg
  config/srparasites/SRParasites.cfg
  config/srparasites/SRParasitesMobs.cfg
  config/srparasites/SRParasitesSystems.cfg
  config/srparasites/SRParasitesWorld.cfg
  config/storagedrawers.cfg
  config/vintagefix.properties
  config/xporbclump.cfg
  groovy/material/ElementMaterials.groovy
  groovy/material/FirstDegreeMaterials.groovy
  groovy/material/IsotopeMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/actinides/UraniumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/nuclear_chemistry/UraniumEnrichment.groovy
  groovy/postInit/mod/Supercritical.groovy
  journeymap/server/5.7/journeymap.server.default.config
  mods/OpenSecurity/assets/opensecurity/sounds/alarms/klaxon1.ogg
  mods/OpenSecurity/assets/opensecurity/sounds/alarms/klaxon2.ogg
  resources/langfiles/lang/en_us.lang
Labels: feature

#1399 Added combustion engine related textures
  resources/gregtech/textures/items/metaitems/engine.crankshaft.png
  resources/gregtech/textures/items/metaitems/engine.piston.png
  resources/gregtech/textures/items/metaitems/engine.spark_plug.png
  resources/gregtech/textures/items/metaitems/sintered_alumina.insulator.png
Labels: enhancement

#1401 Light source susyfication
  groovy/postInit/mod/GregTech.groovy
  groovy/postInit/mod/ProjectRedIllumination.groovy
Labels: enhancement

#1405 Rftools elevator
  config/jei/itemBlacklist.cfg
  groovy/postInit/mod/RFTools.groovy
Labels: enhancement

#1406 Quark stained planks
  groovy/postInit/mod/Quark.groovy
Labels: enhancement

#1400 1 groovy fix, 1 quest fix
  config/betterquesting/DefaultQuests/Quests/0/1107188354.json
  groovy/postInit/mod/ImmersiveRailroading.groovy
Labels: fix

#1402 Questing fixes
  config/betterquesting/DefaultQuests/QuestLines/2.json
  config/betterquesting/DefaultQuests/QuestLines/3.json
  config/betterquesting/DefaultQuests/Quests/2/741.json
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
Labels: fix

#1407 Add recipemap modification methods
  groovy/preInit/MetaClassExpansions.groovy
Labels: internal

#1408 Possibly the most important fix in the history of SUSY
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
  config/betterquesting/resources/supersymmetry/lang/ru_ru.lang
  resources/langfiles/lang/en_pt.lang
  resources/langfiles/lang/en_us.lang
  resources/langfiles/lang/pl_pl.lang
Labels: change

#1409 Migrating recipe maps changes from Susy-Core
  groovy/postInit/mod/GregTechFoodOption.groovy
  groovy/preInit/MetaClassExpansions.groovy
  groovy/preInit/RecipeBuildActions.groovy
  groovy/prePostInit/ModifyRecipeMaps.groovy
Labels: internal

#1390 Combustion engines
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group10/PlatinumGroupChain.groovy
  groovy/postInit/components/CombustionEngines.groovy
  groovy/postInit/mod/MachineRecipes.groovy
  groovy/preInit/RegisterMetaItems.groovy
  groovy/prePostInit/Thermodynamics.groovy
  groovy/prePostInit/oreDict.groovy
  resources/gregtech/models/item/metaitems/engine.crankshaft.json
  resources/gregtech/models/item/metaitems/engine.piston.json
  resources/gregtech/models/item/metaitems/engine.spark_plug.json
  resources/gregtech/models/item/metaitems/sintered_alumina.insulator.json
  resources/gregtech/textures/items/metaitems/engine.crankshaft.png
  resources/gregtech/textures/items/metaitems/engine.piston.png
  resources/gregtech/textures/items/metaitems/engine.spark_plug.png
  resources/gregtech/textures/items/metaitems/sintered_alumina.insulator.png
  resources/langfiles/lang/en_us.lang
Labels: feature
