Repository SymmetricDevs/Supersymmetry, pull requests merged in 2025-07, with the labels that each got.

#1538 I forgor
  resources/langfiles/lang/en_us.lang
Labels: internal

#1537 Fixed sodium dichromate reactions and formulas
  build/questbook.py
  config/betterquesting/resources/supersymmetry/lang/en_us.lang
  groovy/material/FirstDegreeMaterialsA.groovy
  groovy/material/SecondDegreeMaterials.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group6/ChromiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/s_block/group1/SodiumChain.groovy
Labels: fix

#1546 Fix susyId in scripts
  groovy/postInit/gameplay/Drone.groovy
  groovy/postInit/gameplay/QuarryMachine.groovy
  groovy/postInit/metallurgy/StrandCasting.groovy
  groovy/postInit/mod/GregTech.groovy
  groovy/postInit/mod/MachineRecipes.groovy
  groovy/postInit/mod/Pyrotech.groovy
  mods/susycore.pw.toml
Labels: internal

#1550 i deserve a brainrot role for this
  config/rftools/rftools.cfg
Labels: internal

#1547 Update customloadingscreen_tips.txt
  config/customloadingscreen_tips.txt
Labels: change

#1551 add circuit property to coolant
  groovy/classes/ICoolant.groovy
  groovy/prePostInit/Thermodynamics.groovy
Labels: internal

#1552 Plutonium chain & high explosives
  config/biomesoplenty/biome_ids.json
  config/supercritical.cfg
  groovy/material/FirstDegreeMaterialsA.groovy
  groovy/material/FirstDegreeMaterialsB.groovy
  groovy/material/IsotopeMaterials.groovy
  groovy/material/OrganicChemistryMaterials.groovy
  groovy/material/SecondDegreeMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/material/ThirdDegreeMaterials.groovy
  groovy/material/UnknownCompositionMaterials.groovy
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group8/IronChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/actinides/NuclearReprocessing.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/actinides/PlutoniumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/f_block/actinides/UraniumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/p_block/group14/GermaniumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/p_block/group15/NitrogenChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/s_block/group1/SodiumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/elements/s_block/group2/BariumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/isotopes/DeuteriumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/isotopes/UraniumEnrichment.groovy
  groovy/postInit/chemistry/organic_chemistry/ExplosivesChain.groovy
  groovy/postInit/chemistry/organic_chemistry/Extractants.groovy
  groovy/postInit/mod/Supercritical.groovy
  resources/langfiles/lang/en_us.lang
Labels: feature

#1545 Chinese Translation Fix
  resources/langfiles/lang/en_us.lang
  resources/langfiles/lang/zh_cn.lang
Labels: fix

#1560 Fixed diluted sodium sulfate solution distillation to not require HV
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
Labels: fix

#1562 minor bug fixes
  groovy/postInit/chemistry/inorganic_chemistry/elements/s_block/group1/SodiumChain.groovy
  groovy/prePostInit/ModifyRecipeMaps.groovy
Labels: fix

#1558 Misc Fixes
  config/forge.cfg
  config/pyrotech/module.Bucket.cfg
  config/stellar_core.cfg
  mods/biometweakercore.pw.toml
Labels: fix

#1532 Pressurized heavy water reactors & tritium production
  groovy/material/FirstDegreeMaterialsA.groovy
  groovy/material/FirstDegreeMaterialsB.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/material/ThermodynamicsMaterials.groovy
  groovy/postInit/chemistry/ChemistryOverhaul.groovy
  groovy/postInit/chemistry/inorganic_chemistry/isotopes/DeuteriumChain.groovy
  groovy/postInit/chemistry/inorganic_chemistry/isotopes/TritiumChain.groovy
  groovy/postInit/mod/Supercritical.groovy
  groovy/prePostInit/Thermodynamics.groovy
  resources/langfiles/lang/en_us.lang
Labels: feature

#1566 Fix latex collector lang keys
  resources/langfiles/lang/de_de.lang
  resources/langfiles/lang/en_pt.lang
  resources/langfiles/lang/en_us.lang
  resources/langfiles/lang/pl_pl.lang
  resources/langfiles/lang/ru_ru.lang
  resources/langfiles/lang/zh_cn.lang
Labels: fix

#1569 Add flux loading
  config/fluxloading.cfg
  mods/fluxloading.pw.toml
Labels: feature

#1568 Misc fixes (yet again)
  config/BNBGamingCore.cfg
  config/BiomeTweakerCore/BiomeTweakerCore.cfg
  config/ambientsounds-client.json
  config/ambientsounds.cfg
  config/bettermineshafts-1_12_2.cfg
  config/bettermineshafts/1_12_2/README.txt
  config/bettermineshafts/1_12_2/biomeTags.txt
  config/bettermineshafts/1_12_2/variants.json
  config/bettermineshafts/README.txt
  config/betterplacement.cfg
  config/blur.cfg
  config/cosmeticarmorreworked.cfg
  config/ladylib.cfg
  config/noworldgen5you.cfg
  config/overloaded.cfg
  config/quark.cfg
  config/recipehandler.cfg
  config/vanillafix/config_version
  config/vanillafix/methods-stable_39.csv
  groovy/assets/supersymmetry/lang/en_us.lang
  groovy/postInit/mod/JER.groovy
  groovy/preInit/RegisterMetaItems.groovy
  mods/yarcf.pw.toml
  resources/contenttweaker/lang/en_us.lang
  resources/minecraft/textures/gui/container/villager.png
Labels: fix

#1577 Update fluxloading (fixing the resize issue)
  mods/fluxloading.pw.toml
Labels: internal

#1581 I forgor
  CHANGELOG.md
Labels: internal

#1583 update scrit
  mods/supercritical.pw.toml
Labels: internal

#1594 Vanillin recipe accuracy tweaks
  groovy/material/OrganicChemistryMaterials.groovy
  groovy/material/SuSyMaterials.groovy
  groovy/material/UnknownCompositionMaterials.groovy
  groovy/postInit/mod/GregTechFoodOption.groovy
  resources/langfiles/lang/de_de.lang
  resources/langfiles/lang/en_pt.lang
  resources/langfiles/lang/en_us.lang
Labels: fix
