Repository SymmetricDevs/Supersymmetry, pull requests merged in 2025-08, with the labels that each got.

#1599 Fluid compressor <-> fluid decompressor recipes
  groovy/postInit/mod/MachineRecipes.groovy
Labels: change

#1592 Disable mineshaft generation
  config/cavegenerator.cfg
Labels: internal

#1597 feat: boiler rework
  config/jei/itemBlacklist.cfg
  groovy/postInit/gameplay/BoilerTweaks.groovy
  groovy/postInit/mod/GregTech.groovy
  groovy/prePostInit/ModifyRecipeMaps.groovy
Labels: change

#1622 Add circuit to CSTR benzenesulfonic acid to fix recipe collision
  groovy/postInit/chemistry/organic_chemistry/polymers/thermoplastics/PolyetherEtherKetoneChain.groovy
Labels: fix

#1620 Update README.md (clarification)
  README.md
Labels: internal

#1632 pyrochlore reaction stoichiometry
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group5/NiobiumChain.groovy
Labels: fix

#1636 cobalt dupe fix
  groovy/postInit/chemistry/inorganic_chemistry/elements/d_block/group9/CobaltChain.groovy
Labels: fix
